services:
  - type: web
    name: school-app-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://husen20ab_db_user:hOWWOtRx1cEg8jBw@cluster0.neidmqo.mongodb.net/
      - key: CORS_ORIGINS
        value: https://school-logistics.netlify.app
    healthCheckPath: /health

